title: R'lyeh Hacklab
email: contacto@rlab.be
description: >-
  El hacklab es un espacio físico para hackear, aprender a hackear, enseñar a
  hackear, crear, romper arreglar y desarrollar. Hackear no es solo software,
  lo entendemos y extendemos a todas las áreas.
baseurl: ""
url: "https://rlab.be"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
